FROM  maven:3.5-jdk-8-alpine AS build

COPY src /usr/src/app/src  

COPY pom.xml /usr/src/app  

RUN mvn -f /usr/src/app/pom.xml clean package


FROM fabric8/java-alpine-openjdk8-jdk:latest

COPY --from=build /usr/src/app/target/docker-spring-boot.jar /usr/app/Product-1.0.0-SNAPSHOT.jar  

EXPOSE 8080  

ENTRYPOINT ["java","-jar","/usr/app/Product-1.0.0-SNAPSHOT.jar"] 
